services:

  db:
    image: mariadb
    restart: always
    volumes:
      - ./kirameki-structure.sql:/docker-entrypoint-initdb.d/kirameki-structure.sql
    environment:
      # MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: kirameki
      MYSQL_PASSWORD: kiramekipassword
    port: 
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  kirameki:
    image: kirameki
    build: .
    restart: unless-stopped